### ISSUE TITLE
enhancement: make the item disappear after a period of time

### ISSUE THREAD

**Issue by Walking-stone** [Erb3/Cactusfix#1]
This mod is very good, but I have an idea: let the item contact the cactus for a period of time and then disappear, instead of always intact. Of course, it is better to make this setting switchable and the time required for configurable items to break down:)

**Comment by piprett** [comment]
I find it really awesome that people find this mod useful. I am actually very surprised I got my first GitHub issue this fast. Ill do some testing, and thinking before I decide if I would want to add such a feature. Currently my goal is to make a minimalistic mod, and considering items normally de-spawn automatically, I am not too sure if I want to add this. Thanks for the suggestion tho, and thanks for using the mod!

**Comment by piprett** [comment]
I've ended up on that, while I want people to use my mods, I don't think this change is necessary. Items de-spawn like usual after five minutes. If you have a usecase for this functionality, please leave a comment and ill consider it again.

Thanks!
